import type { WeaponDef } from "./types.js";

/**
 * The full original arsenal. Every weapon is config-driven: the server resolves
 * behavior from `class` + fields here, the client resolves visuals/audio from
 * `particle`/`audio` keys. Balance changes never require code changes.
 */
export const WEAPONS: WeaponDef[] = [
  {
    id: "inflatable_mallet",
    name: "Inflatable Mallet",
    description: "A giant squeaky hammer. Medium damage, absurd knockback.",
    rarity: "uncommon",
    class: "melee",
    damage: 9,
    knockback: 16,
    range: 2.3,
    attackIntervalMs: 700,
    cooldownMs: 0,
    durability: 14,
    aim: "auto",
    audio: "squeak",
    particle: "starBurst",
    announcerLine: "That mallet is 90% air and 100% disrespect!",
  },
  {
    id: "pool_noodle",
    name: "Tactical Pool Noodle",
    description: "Fast, low-damage jabs with embarrassing sound effects.",
    rarity: "common",
    class: "melee",
    damage: 4,
    knockback: 5,
    range: 2.6,
    attackIntervalMs: 260,
    cooldownMs: 0,
    durability: 30,
    aim: "auto",
    audio: "thwip",
    particle: "softPuff",
  },
  {
    id: "folding_chair",
    name: "Folding Chair of Questionable Legality",
    description: "Slow but devastating. Swing it or throw it.",
    rarity: "rare",
    class: "melee",
    damage: 16,
    knockback: 14,
    range: 2.2,
    attackIntervalMs: 1000,
    cooldownMs: 0,
    durability: 8,
    aim: "auto",
    audio: "clang",
    particle: "metalSpark",
    announcerLine: "A FOLDING CHAIR?! Someone call the league office!",
  },
  {
    id: "leaf_blower",
    name: "Leaf Blower of Destiny",
    description: "A cone of wind that shoves fighters and furniture alike.",
    rarity: "rare",
    class: "cone",
    damage: 1,
    knockback: 11,
    range: 5.5,
    attackIntervalMs: 200,
    cooldownMs: 0,
    durability: 60,
    pushForce: 14,
    aim: "direction",
    audio: "blower",
    particle: "windLines",
  },
  {
    id: "foam_finger_cannon",
    name: "Foam Finger Cannon",
    description: "Fires oversized foam fingers that send fighters flying.",
    rarity: "uncommon",
    class: "projectile",
    damage: 7,
    knockback: 13,
    range: 16,
    attackIntervalMs: 650,
    cooldownMs: 0,
    durability: 12,
    projectileSpeed: 16,
    projectileRadius: 0.5,
    aim: "auto",
    audio: "foomp",
    particle: "foamTrail",
  },
  {
    id: "support_brick",
    name: "Emotional-Support Brick",
    description: "A small throwable brick. Holding it grants inexplicable confidence (+10% speed).",
    rarity: "common",
    class: "thrown",
    damage: 12,
    knockback: 9,
    range: 14,
    attackIntervalMs: 500,
    cooldownMs: 0,
    durability: 1,
    projectileSpeed: 18,
    projectileRadius: 0.35,
    selfSpeedBoost: 1.1,
    aim: "auto",
    audio: "whiff",
    particle: "dustPuff",
  },
  {
    id: "budget_laser_sword",
    name: "Budget Laser Sword",
    description: "Glows inconsistently. Occasionally makes the wrong sound.",
    rarity: "legendary",
    class: "melee",
    damage: 14,
    knockback: 10,
    range: 2.5,
    attackIntervalMs: 380,
    cooldownMs: 0,
    durability: 22,
    aim: "auto",
    audio: "laserMaybe",
    particle: "neonSlash",
    announcerLine: "The Budget Laser Sword! Batteries not included, mercy not available!",
  },
  {
    id: "flying_croc",
    name: "Flying Croc",
    description: "A throwable foam shoe that curves toward nearby targets.",
    rarity: "common",
    class: "thrown",
    damage: 8,
    knockback: 7,
    range: 15,
    attackIntervalMs: 450,
    cooldownMs: 0,
    durability: 3,
    projectileSpeed: 14,
    projectileRadius: 0.4,
    homing: 0.5,
    aim: "auto",
    audio: "whoosh",
    particle: "shoeSpin",
  },
  {
    id: "karaoke_mic",
    name: "Broken Karaoke Microphone",
    description: "Emits a painful feedback wave in front of the singer.",
    rarity: "rare",
    class: "cone",
    damage: 6,
    knockback: 8,
    range: 4.5,
    attackIntervalMs: 550,
    cooldownMs: 0,
    durability: 16,
    pushForce: 6,
    aim: "direction",
    audio: "feedback",
    particle: "soundRings",
  },
  {
    id: "commissioners_gavel",
    name: "Commissioner's Gavel",
    description: "Heavy justice. Booms 'ORDER!' on impact.",
    rarity: "legendary",
    class: "melee",
    damage: 20,
    knockback: 19,
    range: 2.4,
    attackIntervalMs: 1100,
    cooldownMs: 0,
    durability: 10,
    aim: "auto",
    audio: "gavel",
    particle: "orderShock",
    announcerLine: "ORDER IN THE ARENA! The gavel has spoken!",
  },
  {
    id: "pizza_roll_bag",
    name: "Frozen Pizza Roll Bag",
    description: "Hurls a spread of molten-hot pizza rolls.",
    rarity: "uncommon",
    class: "spread",
    damage: 5,
    knockback: 6,
    range: 12,
    attackIntervalMs: 800,
    cooldownMs: 0,
    durability: 8,
    projectileSpeed: 13,
    projectileRadius: 0.3,
    spreadCount: 5,
    spreadAngleDeg: 40,
    aim: "auto",
    audio: "sizzle",
    particle: "steamPuff",
  },
  {
    id: "glitter_grenade",
    name: "Glitter Grenade",
    description: "Sparkling explosion that briefly blinds everyone nearby.",
    rarity: "rare",
    class: "thrown",
    damage: 6,
    knockback: 10,
    range: 13,
    attackIntervalMs: 700,
    cooldownMs: 0,
    durability: 2,
    projectileSpeed: 12,
    projectileRadius: 0.35,
    aoeRadius: 3.5,
    blind: true,
    aim: "auto",
    audio: "sparklePop",
    particle: "glitterBlast",
  },
  {
    id: "passive_aggressive_email",
    name: "Passive-Aggressive Email",
    description: "A homing envelope. 'Per my last message…' Slows its victim.",
    rarity: "uncommon",
    class: "projectile",
    damage: 4,
    knockback: 3,
    range: 20,
    attackIntervalMs: 900,
    cooldownMs: 0,
    durability: 6,
    projectileSpeed: 10,
    projectileRadius: 0.4,
    homing: 0.85,
    slowFactor: 0.6,
    aim: "auto",
    audio: "sendWoosh",
    particle: "paperFlutter",
  },
  {
    id: "tiny_shopping_cart",
    name: "Tiny Shopping Cart",
    description: "Rideable charge weapon. Steering is a suggestion.",
    rarity: "questionable",
    class: "ride",
    damage: 13,
    knockback: 15,
    range: 0,
    attackIntervalMs: 250,
    cooldownMs: 4000,
    durability: 6,
    selfSpeedBoost: 1.9,
    aim: "direction",
    audio: "rattle",
    particle: "sparkTrail",
    announcerLine: "Someone is RIDING THE CART. This is why we can't have nice leagues.",
  },
  {
    id: "gas_station_hot_dog",
    name: "Gas-Station Hot Dog",
    description: "Throwable. Leaves a slippery mustard trail of regret.",
    rarity: "common",
    class: "thrown",
    damage: 7,
    knockback: 6,
    range: 13,
    attackIntervalMs: 550,
    cooldownMs: 0,
    durability: 3,
    projectileSpeed: 15,
    projectileRadius: 0.35,
    trail: "mustard",
    aim: "auto",
    audio: "splat",
    particle: "mustardSplat",
  },
  {
    id: "plunger_launcher",
    name: "Plunger Launcher",
    description: "Fires a plunger that yanks the victim toward you.",
    rarity: "rare",
    class: "projectile",
    damage: 4,
    knockback: -12, // negative knockback = pull
    range: 14,
    attackIntervalMs: 1000,
    cooldownMs: 0,
    durability: 9,
    projectileSpeed: 17,
    projectileRadius: 0.4,
    aim: "auto",
    audio: "plunk",
    particle: "suctionRings",
  },
  {
    id: "rubber_chicken_nunchucks",
    name: "Rubber Chicken Nunchucks",
    description: "Two chickens, one string, zero dignity. Very fast.",
    rarity: "uncommon",
    class: "melee",
    damage: 5,
    knockback: 6,
    range: 2.4,
    attackIntervalMs: 220,
    cooldownMs: 0,
    durability: 26,
    aim: "auto",
    audio: "bwok",
    particle: "featherPuff",
  },
  {
    id: "birthday_cake_bomb",
    name: "Exploding Birthday Cake",
    description: "Timed explosive. The candles count down. Make a wish.",
    rarity: "legendary",
    class: "thrown",
    damage: 18,
    knockback: 17,
    range: 12,
    attackIntervalMs: 800,
    cooldownMs: 0,
    durability: 2,
    projectileSpeed: 10,
    projectileRadius: 0.45,
    aoeRadius: 4.2,
    fuseMs: 1800,
    aim: "auto",
    audio: "partyBoom",
    particle: "cakeBlast",
    announcerLine: "Happy birthday to WHOEVER IS STANDING NEXT TO THAT CAKE!",
  },
  {
    id: "hot_sauce_flamethrower",
    name: "Hot-Sauce Flamethrower",
    description: "Short-range stream of cartoon fire and instant regret.",
    rarity: "legendary",
    class: "cone",
    damage: 4,
    knockback: 3,
    range: 4.2,
    attackIntervalMs: 150,
    cooldownMs: 0,
    durability: 70,
    pushForce: 2,
    aim: "direction",
    audio: "spicy",
    particle: "cartoonFlame",
  },
  {
    id: "office_chair_launcher",
    name: "Office Chair Launcher",
    description: "Launches rolling office chairs across the arena.",
    rarity: "questionable",
    class: "projectile",
    damage: 11,
    knockback: 14,
    range: 18,
    attackIntervalMs: 1200,
    cooldownMs: 0,
    durability: 5,
    projectileSpeed: 12,
    projectileRadius: 0.6,
    aim: "auto",
    audio: "wheelieClatter",
    particle: "chairTumble",
    announcerLine: "Ergonomic DESTRUCTION incoming!",
  },
];

export const WEAPONS_BY_ID: ReadonlyMap<string, WeaponDef> = new Map(WEAPONS.map((w) => [w.id, w]));

export function getWeapon(id: string): WeaponDef {
  const w = WEAPONS_BY_ID.get(id);
  if (!w) throw new Error(`Unknown weapon: ${id}`);
  return w;
}
